# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'NativeComponent' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

    pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga/yoga.podspec'
    pod 'React', path: '../node_modules/react-native', :subspecs => [
        'Core',
        'CxxBridge',
        'DevSupport',
        'RCTActionSheet',
        'RCTAnimation',
        'RCTGeolocation',
        'RCTImage',
        'RCTLinkingIOS',
        'RCTNetwork',
        'RCTSettings',
        'RCTText',
        'RCTVibration',
        'RCTWebSocket',
        'RCTPushNotification'
    ]
    pod 'DoubleConversion', podspec: '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
    pod 'Folly', podspec: '../node_modules/react-native/third-party-podspecs/Folly.podspec'
    pod 'glog', podspec: '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'RNReanimated', :path => '../node_modules/react-native-reanimated'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == "React"
      target.remove_from_project
    end
   end
end
